### ISSUE TITLE
xud-simnet-channels always different

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-simnet#17]
xud-simnet-1 on vm-1
```
vagrant@xud-simnet-1:~$ xucli listpeers
{
  "peersList": [
    {
      "address": "xud3.test.exchangeunion.com:8885",
      "nodePubKey": "03fd337659e99e628d0487e4f87acf93e353db06f754dccc402f2de1b857a319d0",
      "lndBtcPubKey": "030c2ffd29a92e2dd2fb6fb046b0d9157e0eda8b11caa0e439d0dd6a46a444381c",
      "lndLtcPubKey": "02f5e0324909bdb635d4d6a50aa07c517db59f5d18219fd058f9faa3ef3a1fd83a",
      "inbound": false,
      "pairsList": [
        "LTC/BTC"
      ],
      "xudVersion": "1.0.0-alpha.5",
      "secondsConnected": 48
    },
    {
      "address": "xud1.test.exchangeunion.com:8885",
      "nodePubKey": "02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6",
      "lndBtcPubKey": "02d693d951ce4fc116b2b5e22e8e4966dd3cf9ad7600b8de24190d6af429f260c0",
      "lndLtcPubKey": "03114cda7206e92def08a35fc4039aba59394604fef9171ef19dbd5f938ce9387b",
      "inbound": false,
      "pairsList": [
        "LTC/BTC"
      ],
      "xudVersion": "1.0.0-alpha.5",
      "secondsConnected": 48
    }
  ]
}
```

xud-simnet-2 on vm-2
```
vagrant@xud-simnet-2:~/xud-simnet/xud$ xucli listpeers
{
  "peersList": [
    {
      "address": "xud1.test.exchangeunion.com:8885",
      "nodePubKey": "02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6",
      "lndBtcPubKey": "02d693d951ce4fc116b2b5e22e8e4966dd3cf9ad7600b8de24190d6af429f260c0",
      "lndLtcPubKey": "03114cda7206e92def08a35fc4039aba59394604fef9171ef19dbd5f938ce9387b",
      "inbound": false,
      "pairsList": [
        "LTC/BTC"
      ],
      "xudVersion": "1.0.0-alpha.5",
      "secondsConnected": 140
    },
    {
      "address": "xud3.test.exchangeunion.com:8885",
      "nodePubKey": "03fd337659e99e628d0487e4f87acf93e353db06f754dccc402f2de1b857a319d0",
      "lndBtcPubKey": "030c2ffd29a92e2dd2fb6fb046b0d9157e0eda8b11caa0e439d0dd6a46a444381c",
      "lndLtcPubKey": "02f5e0324909bdb635d4d6a50aa07c517db59f5d18219fd058f9faa3ef3a1fd83a",
      "inbound": false,
      "pairsList": [
        "LTC/BTC"
      ],
      "xudVersion": "1.0.0-alpha.5",
      "secondsConnected": 140
    }
  ]
}
```

xud-simnet-1
```
± % python engine.py                                                                                            !6789

> connect
Connected to xud 1.0.0-alpha.5 pub_key: 037c514ee25ebbfc10726442325bdf3210b6ee80a9b3618aa96788a06b01696535

Currency Pairs: LTC/BTC

BTC Lightning Channels: 3
LTC Lightning Channels: 3
```

xud-simnet-2
```
± % python engine.py                                                                                            !6789

> connect localhost 9886 ./tls2.cert
Connected to xud 1.0.0-alpha.5 pub_key: 03d1b2fa7af9ff300e00fd9c3eb54ac8481914b19603e58b4c06430449ad87ad89

Currency Pairs: LTC/BTC

BTC Lightning Channels: 1
LTC Lightning Channels: 2
```

vm-1 and vm-2 are on the same host machine.

**Comment by kilrau** [comment]
How it is: `xud-simnet-install` and also `xud-simnet-channels` create different channels to different peers every time. Never to all (see above)

How it should be: `xud-simnet-install` and also `xud-simnet-channels` always create channels to all connected peers (4 in the case above: xud1,2,3 & 2nd local instance)

**Comment by offerm** [comment]
xud-simnet-install does not create any channels.

xud-simnet-channels creates one BTC channel and one LTC channel. It
randomly select LNDBTC and LNDLTC belonding to test1,test2,test3 and
connect to them. this leads to the creating of LND channels.

Example:
Say you install a new node.   xud-simnet-channels selects (for example)
test2 for BTC channel and test3 for LTC channel. The script connects the
local LNDBTC to test2's LNDBTC and local LNDLTC to test3's LNDLTC. On test2
and test3 the bot will detect these connection and creates an LND channel
from test2 to the new node (BTC) and from test3 to the new node (LTC).

These LND channels can be used to swap between the local XUD node and any
of the test nodes. reason is - the test nodes are connected between
themselves. Actually, you can trade between your local XUD and any other
XUD connected properly to the simulation network,

There is not need to create channels to all peers (really not scalable).

The peers are selected randomly to create load balancing between the test
nodes.

You have several channels since xud-simnet-coneect executed multiple times.
No need to do that.

See no issue here.

**Comment by kilrau** [comment]
> There is not need to create channels to all peers (really not scalable). The peers are selected randomly to create load balancing between the test nodes. You have several channels since xud-simnet-connect executed multiple times. No need to do that.

Not scalable in the long-term, but that's what we'd expect and want exchanges to do in the beginning to eliminate all sorts of routing errors. Just like the one we have right now. Please set up SIMNET to create channels to xud1,2 & 3 for now.

**Comment by offerm** [comment]
Still see no reason for it.

See https://github.com/ExchangeUnion/xud/issues/745

**Comment by kilrau** [comment]
agree to hold off on this
