### ISSUE TITLE
Upgrade our hosted btcd,ltcd,geth,lndbtc,lndltc,raiden to latest version

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-simnet#65]
`btcd-simnet` is the instance that hosts btcd,ltcd and geth as well as lnd's & raiden at the moment, which are mining our own simnet chain.

Step 1 would be to update these all to the latest versions (especially https://github.com/ltcsuite/ltcd/releases). We might be running our own fork to make mining the simnet chain possible:
- use https://github.com/ExchangeUnion/raiden/ (don't change anything)
- check https://github.com/ExchangeUnion/go-ethereum
- check https://github.com/ExchangeUnion/btcd

Everything currently running should be located in `/home/xud` on the instance.

Securely, making sure nothing breaks. E.g. we could clone the instance, and/or re-create the chains in a new instance, starting mining from scratch, essentially creating a new simnet, all fine.

**Comment by michael1011** [comment]
I updated LTCD to the latest master for #63

**Comment by LePremierHomme** [comment]
Updates:
* `go` was upgraded to 1.13
* `ltcd` was rebuilt with latest `go`
* `btcd` was upgraded to v0.20.1-beta
* `geth` was upgraded to v1.9.11
* xud2/3 instances got turned off. Reasons: high maintenance effort and connext will not allow multi-hop trades anyways in future
* It was decided not to upgrade LND on xud1 for now

Current issue:
Connecting with `raiden` via simnet setup to `geth` rpc endpoint doesn’t work well. It’s crashing with this error after launch, or about 1 min later:
```
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='35.231.222.142', port=8546): Read timed out. (read timeout=10)
```
It doesn’t looks like a problem with the initial connection, which will cause it to close immediately with a different error.
Regarding the connection inspection: tcp layer works fine, but i’m failing to connect to it with a web3 test app I made (which connects to a local `geth` fine). Because I don’t think `raiden` has a problem with the initial connection, i’m a bit confused with the situation here.

**Comment by kilrau** [comment]
All done, closing.
